export const ROUTES = {
  onboarding: '/pages/onboarding/index',
  home: '/pages/home/index',
  atlas: '/pages/atlas/index',
  mine: '/pages/mine/index',
  favorites: '/pages/favorites/index',
  records: '/pages/records/index',
  citySettings: '/pages/settings/city',
  reminderSettings: '/pages/settings/reminder',
  feedback: '/pages/feedback/index',
  privacy: '/pages/legal/privacy',
  terms: '/pages/legal/terms',
  about: '/pages/about/index',
  tipsDetail: '/pages/tips/detail',
  knowledge: '/pages/knowledge/index',
  interaction: '/pages/interaction/index',
  petDetail: '/pages/pet/detail',
} as const
